version: 0.2
env:
  variables:
    APP_NAME: "BDP-BBC-UIPortal"
phases:
  install:
    runtime-versions:
      nodejs: 18.x
    commands:
      - echo install process started on `date`
      - npm install && npm install -g @angular/cli
  build:
    commands:
      - echo Build started on `date`
      - ng build --configuration=production
  post_build:
    commands:
      - echo build process finised on `date`
      - mv deploy.json package.json 
artifacts:
  type: zip
  files:
      - dist/**/*
      - package.json
      - app.js
      - .ebextensions/**/*